apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnavi4-ai
  namespace: sk-team-04
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gnavi4-ai
  template:
    metadata:
      labels:
        app: gnavi4-ai
    spec:
      serviceAccountName: default
      containers:
        - name: webserver
          image: amdp-registry.skala-ai.com/skala25a/sk-gnavi4-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: OPENAI_API_KEY
            - name: CHROMA_HOST
              value: "chromadb-1.chromadb"
            - name: CHROMA_PORT
              value: "8000"
            - name: CHROMA_AUTH_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: CHROMA_AUTH_CREDENTIALS
            - name: CHROMA_COLLECTION_NAME
              value: "gnavi4_prod_collection"
            - name: CHROMA_USE_EXTERNAL
              value: "false"
            # PVC 설정
            - name: APP_STORAGE_PVC_PATH
              value: "/mnt/gnavi"
            - name: APP_STORAGE_BASE_URL
              value: "https://sk-gnavi4.skala25a.project.skala-ai.com"
          # 볼륨 마운트
          volumeMounts:
            - name: storage-volume
              mountPath: /mnt/gnavi

      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: efs-sc-gnavi4
