apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnavi4-ai
  namespace: sk-team-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnavi4-ai
  template:
    metadata:
      labels:
        app: gnavi4-ai
    spec:
      serviceAccountName: default
      containers:
        - name: webserver
          image: amdp-registry.skala-ai.com/skala25a/sk-gnavi4-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: OPENAI_API_KEY
            - name: CHROMA_HOST
              value: "chromadb-1.chromadb"
            - name: CHROMA_PORT
              value: "8000"
            - name: CHROMA_AUTH_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: CHROMA_AUTH_CREDENTIALS
            - name: CHROMA_COLLECTION_NAME
              value: "gnavi4_prod_collection"
            - name: CAREER_CHROMA_COLLECTION_NAME
              value: "gnavi4_career_history_prod"
            - name: CHROMA_USE_EXTERNAL
              value: "false"
            - name: VECTORDB_CACHE_DIR # gnavi-ai Pod 내 임시 캐시 경로
              value: "/tmp/embedding_cache"
            - name: CAREER_CSV_PATH
              value: "/app/data/csv/career_history_v2.csv"
