apiVersion: v1
kind: Service
metadata:
  name: gnavi4-ai
  namespace: sk-team-04
spec:
  selector:
    app: gnavi4-ai
  ports:
    - name: http
      protocol: TCPs
      port: 8001
      targetPort: 8001
  type: ClusterIP
